config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'static_pages#home', as: 'home'

  resources :users

  # Routes pour les gestions de session :
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :fname,  presence: true, length: { maximum: 50 }
  validates :lname,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,  presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Login Completed"
      redirect_to home_path

    else
      flash.now[:danger] = 'Invalid'
      redirect_to login_path
    end
  end


  def destroy
    log_out
    redirect_to home_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if @user.save
      log_in @user
      redirect_to home_path
    else
      flash[:danger] = "essai encore"
      redirect_to new_user_path
  end

  def index
    @users = User.all
  end



  private

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password) # Sécurité obligatoire : ca vérifie que le paramètre renvoi que des attributs de user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddPrivateClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Club privée de la swagance</h1>

<% if logged_in? %>
  <p>Bienvenue <%= current_user.fname %></p>
  <p><a href="<%= users_path %>"><button type="button" name="button">Consulter les membres du clan</button></a></p>
  <p><%= button_to "Me déconnecter", logout_path, method: "delete" %></p>


<% else %>
  <p>Tu es déja inscrit ?</p>
  <p><a href="<%= login_path %>"><button type="button" name="button">Me connecter</button></a></p>

  <p>Crée ton compte dès maintenant !</p>
  <p><a href="<%= new_user_path %>"><button type="button" name="button">M'inscrire</button></a></p><br><br>

<% end %>

app/views/users/index.html.erb
<p><a href="<%= home_path %>"><button type="button" name="button">Revenir à la page d'accueil</button></a></p>

<h1>Membres</h1>

<% @users.each do |user| %>

  <h2>Utilisateur n°<%= user.id %> :</h2>
  Prénom : <%= user.fname %><br>
  Nom : <%= user.lname %><br>
  Mail : <%= user.email %><br>

<% end %>

app/views/users/new.html.erb
<h1>Création d'un compte</h1>

<p>Entre tes infos</p><br>

<%= form_for @user do |f| %>

  <%= label_tag 'Ton prénom :' %>
  <%= f.text_field :fname, placeholder: "Jean-Michel" %><br>

  <%= label_tag 'Ton nom :' %>
  <%= f.text_field :lname, placeholder: "Blancoeur" %><br>

  <%= label_tag 'email:' %>
  <%= f.text_field :email, placeholder: "michou@gmail.com"%><br>

  <%= label_tag 'password:' %>
  <%= f.text_field :password %><br>

  <%= f.submit "Je m'enregistre !" %>

<% end %>

<p><a href="<%= home_path %>"><button type="button" name="button">Revenir à la page d'accueil</button></a></p>